name: "Cloud Run Deploy"

on:
  push:
    branches: [develop]
    paths:
      - backend/williams/terraform/**
      - backend/williams/src/**
      - backend/williams/db/**
      - backend/williams/games/**
  pull_request:
    branches: [develop]
    paths:
      - backend/williams/terraform/**

jobs:
  docker-deploy:
    if: github.event_name == 'push'
    uses: ./.github/workflows/williams.backend.docker_deploy.yml
    with:
      IMAGE_NAME: europe-west2-docker.pkg.dev/dorilton-motor-sports/dms/dms-cloud-run:${{ github.sha }}
      REGION: europe-west2
      WORKING_DIRECTORY: backend
      DOCKERFILE_LOCATION: williams/Dockerfile
    secrets:
      GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT }}
  docker-deploy-acc-launcher:
    if: github.event_name == 'push'
    uses: ./.github/workflows/williams.backend.docker_deploy.yml
    with:
      IMAGE_NAME: gcr.io/dorilton-motor-sports/acc-launcher:${{ github.sha }}
      REGION: us-central1
      WORKING_DIRECTORY: backend/williams/games/acc/launcher
    secrets:
      GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT }}
  docker-deploy-acc-server:
    if: github.event_name == 'push'
    uses: ./.github/workflows/williams.backend.docker_deploy_acc.yml
    with:
      IMAGE_NAME: gcr.io/dorilton-motor-sports/acc-server:latest
      REGION: us-central1
      WORKING_DIRECTORY: backend/williams/games/acc/server
    secrets:
      GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT }}
      STEAM_APP_ID: ${{ secrets.STEAM_APP_ID }}
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
      STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}
  terraform-deploy:
    if: always()
    uses: ./.github/workflows/williams.backend.terraform_deploy.yml
    needs:
      - docker-deploy
      - docker-deploy-acc-launcher
      - docker-deploy-acc-server
    with:
      WORKSPACE: ${{ github.ref == 'refs/heads/main' && 'prd' || 'stg' }}
      IMAGE_NAME: europe-west2-docker.pkg.dev/dorilton-motor-sports/dms/dms-cloud-run:${{ github.sha }}
      REGION: europe-west2
      LAUNCHER_IMAGE_NAME: gcr.io/dorilton-motor-sports/acc-launcher:${{ github.sha }}
      LAUNCHER_REGION: us-central1
    secrets:
      GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT }}
      TERRAFORM_API_TOKEN: ${{ secrets.TERRAFORM_API_TOKEN }}
      SERVICE_ACCOUNT_NAME: ${{ github.ref == 'refs/heads/main' && secrets.CLOUD_SERVICE_ACCOUNT_EMAIL_PRD || secrets.CLOUD_SERVICE_ACCOUNT_EMAIL_STG }}
  database-migrate:
    if: github.event_name == 'push'
    uses: ./.github/workflows/williams.backend.database_migrate.yml
    needs: terraform-deploy
    secrets:
      GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT }}
