name: "Refresh ACC Game Server Docker Image"

on:
  schedule:
    - cron: "0 * * * *"

jobs:
  docker-refresh-acc-server:
    uses: ./.github/workflows/williams.backend.docker_deploy_acc.yml
    with:
      IMAGE_NAME: gcr.io/dorilton-motor-sports/acc-server:latest
      REGION: us-central1
      WORKING_DIRECTORY: backend/williams/games/acc/server
    secrets:
      GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT: ${{ secrets.GOOGLE_CLOUD_GITHUB_SERVICE_ACCOUNT }}
      STEAM_APP_ID: ${{ secrets.STEAM_APP_ID }}
      STEAM_USERNAME: ${{ secrets.STEAM_USERNAME }}
      STEAM_PASSWORD: ${{ secrets.STEAM_PASSWORD }}